version: '3.4'

services:
    backend:
        build:
            context: .
            target: builded
        container_name: backend
        environment:
            - spring.data.neo4j.uri=bolt://neo4j-db:7687
        ports:
            - 8080:8080
        command: sh -c "java -Djava.security.egd=file:/dev/./urandom -jar /app/target/dependency-scan_backend.jar"
        depends_on:
            - neo4j-db
        networks:
            - dependency-scan

    neo4j-db:
        image: neo4j:4.1.3
        container_name: neo4j-db
        volumes:
            - /opt/neo4j/data/conf:/conf
            - /opt/neo4j/data/data:/data
            - /opt/neo4j/data/import:/import
            - /opt/neo4j/data/logs:/logsneo4j
        environment:
            NEO4J_AUTH: neo4j/password
        ports:
            - 7687:7687 #Bolt, sicheres, binäres Zugriffsprotokoll
            - 7474:7474 #HTTP
        networks:
            - dependency-scan

networks:
    dependency-scan:
        driver: bridge
