version: '3.4'

services:
    frontend:
        build:
            context: ./frontend
            target: dependency-scan_frontend
        # restart: always
        ports:
            - 80:80
        depends_on: # start the depends_on first
            - backend
        networks:
            - app-network

    backend:
        build:
            context: ./backend
            target: dependency-scan_backend
        container_name: backend
        environment:
            - spring.data.neo4j.uri=bolt://neo4j-db:7687
        ports:
            - 8080:8080
        depends_on:
            - neo4j-db
        networks:
            - app-network

    neo4j-db:
        image: neo4j:4.1.3
        container_name: neo4j-db
        volumes:
            - ./neo4j/data/conf:/conf
            - ./neo4j/data/data:/data
            - ./neo4j/data/import:/import
            - ./neo4j/data/logs:/logsneo4j
        restart: always
        environment:
            NEO4J_AUTH: neo4j/password
        ports:
            - 7474:7474 #HTTP
            - 7687:7687 #Bolt, secure, binary access log
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
