version: '3.4'

services:
    development:
        build:
            context: .
            target: unittesting
        volumes:
            - .:/app
        ports:
            - 4200:4200
            - 9876:9876
        command: sh -c "npm install && (ng serve --host 0.0.0.0 & ng test)"
